kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-elstic02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/elastic02"
